# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_instance <- function() {
    .Call(`_libpressio_get_instance`)
}

get_compressor <- function(library, name) {
    .Call(`_libpressio_get_compressor`, library, name)
}

get_io <- function(library, name) {
    .Call(`_libpressio_get_io`, library, name)
}

compressor_compress <- function(compressor, input, output) {
    invisible(.Call(`_libpressio_compressor_compress`, compressor, input, output))
}

compressor_decompress <- function(compressor, input, output) {
    invisible(.Call(`_libpressio_compressor_decompress`, compressor, input, output))
}

compressor_get_options <- function(compressor) {
    .Call(`_libpressio_compressor_get_options`, compressor)
}

compressor_get_configuration <- function(compressor) {
    .Call(`_libpressio_compressor_get_configuration`, compressor)
}

compressor_get_metrics_results <- function(compressor) {
    .Call(`_libpressio_compressor_get_metrics_results`, compressor)
}

compressor_set_options <- function(compressor, options) {
    invisible(.Call(`_libpressio_compressor_set_options`, compressor, options))
}

io_read_with_template <- function(io, data_template) {
    .Call(`_libpressio_io_read_with_template`, io, data_template)
}

io_write <- function(io, data) {
    invisible(.Call(`_libpressio_io_write`, io, data))
}

io_read <- function(io) {
    .Call(`_libpressio_io_read`, io)
}

io_get_options <- function(io) {
    .Call(`_libpressio_io_get_options`, io)
}

io_set_options <- function(io, options) {
    invisible(.Call(`_libpressio_io_set_options`, io, options))
}

supported_compressors <- function() {
    .Call(`_libpressio_supported_compressors`)
}

supported_metrics <- function() {
    .Call(`_libpressio_supported_metrics`)
}

supported_io <- function() {
    .Call(`_libpressio_supported_io`)
}

data_to_R <- function(ptr) {
    .Call(`_libpressio_data_to_R`, ptr)
}

data_new_empty <- function(dtype, dims) {
    .Call(`_libpressio_data_new_empty`, dtype, dims)
}

data_new_owning <- function(dtype, dims) {
    .Call(`_libpressio_data_new_owning`, dtype, dims)
}

io_data_path_read <- function(dims, filepath) {
    .Call(`_libpressio_io_data_path_read`, dims, filepath)
}

data_new_clone <- function(ptr) {
    .Call(`_libpressio_data_new_clone`, ptr)
}

data_from_R <- function(obj) {
    .Call(`_libpressio_data_from_R`, obj)
}

data_from_R_typed <- function(obj, type) {
    .Call(`_libpressio_data_from_R_typed`, obj, type)
}

options_from_R_typed <- function(l, option_types) {
    .Call(`_libpressio_options_from_R_typed`, l, option_types)
}

options_from_R <- function(l) {
    .Call(`_libpressio_options_from_R`, l)
}

options_from_json <- function(json_str) {
    .Call(`_libpressio_options_from_json`, json_str)
}

options_to_R <- function(ptr) {
    .Call(`_libpressio_options_to_R`, ptr)
}

options_to_string <- function(ptr) {
    .Call(`_libpressio_options_to_string`, ptr)
}

data_to_string <- function(ptr) {
    .Call(`_libpressio_data_to_string`, ptr)
}

